eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}

server:
  port: 8711

spring:
  application:
    name: ceshi-consumer
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 100
    timeout: 3000
  main:
    allow-bean-definition-overriding: true

swagger:
  basepackage: com.edh.controller
  title: miamisys
  descri: 家校通
  version: 1.0
  contact: 家校通
  url: http://localhost:8701/value
feign:
  client:
    config:
      default:
        connectTimeout: 1000000
        readTimeout: 1200000
