eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}
server:
  port: 8500

spring:
  application:
    name: zull
zuul:
  routes:
    basic:
      servicesId: ceshi-consumer
