server:
  port: 8702

spring:
  application:
    name: student-consumer
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 100
    timeout: 3000
swagger:
  basepackage: com.edh.controller
  title: miamisys
  descri: 家校通
  version: 1.0
  contact: 白大闲人
  url: http://localhost:8701/value
feign:
  client:
    config:
      default:
        connectTimeout: 1000000
        readTimeout: 1200000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}